# Generated by Django 2.2 on 2021-02-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasi',
            name='nama',
            field=models.CharField(max_length=15),
        ),
    ]
